services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app 
    networks:
      - mynetwork
    stdin_open: true 
    tty: true    
    deploy:
      replicas: 2    

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    networks:
      - mynetwork
    stdin_open: true 
    tty: true       

networks:
  mynetwork:
    driver: bridge